"""The VPinPlay Multi page's guests, which are core's.

A profile is a guest holding a VPinPlay account; the one up is active. Joining, choosing
and leaving go through the same core path as the Console and the phone.
"""

from __future__ import annotations

from typing import Any

from common.extensions import temporary_profiles
from common.service_errors import ServiceError


def activate_profile_from_upload(filename: str, content: bytes) -> dict[str, Any]:
    """A guest joins from a card file. Raises ValueError with why it was not taken."""
    if not content:
        raise ValueError("Uploaded file is empty.")
    try:
        text = content.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ValueError("Uploaded file must be a UTF-8 SVG generated by VPinFE.") from exc
    try:
        return temporary_profiles.join(text)
    except ServiceError as exc:
        raise ValueError(str(exc)) from exc


def clear_profile() -> dict[str, Any]:
    return temporary_profiles.clear()


def clear_profile_by_key(profile_key: str) -> dict[str, Any]:
    """That guest signed out; one already gone leaves nothing to do."""
    try:
        return temporary_profiles.leave(profile_key)
    except ServiceError:
        return temporary_profiles.state()


def set_current_profile(profile_key: str) -> dict[str, Any]:
    return temporary_profiles.choose(profile_key)


def get_profile_status() -> dict[str, Any]:
    return temporary_profiles.state()
