from __future__ import annotations

import json
import re
from html import unescape
from typing import Any
from xml.etree import ElementTree

from common.vpinplay_runtime import (
    activate_alternate_profile,
    clear_alternate_profile,
    get_alternate_profile_state,
    set_active_profile,
    validate_profile_payload,
)


_PAYLOAD_COMMENT_RE = re.compile(r"<!--\s*VPINPLAY_PAYLOAD:(.*?)-->", re.DOTALL)


def _extract_payload_text_from_svg(svg_text: str) -> str:
    comment_match = _PAYLOAD_COMMENT_RE.search(svg_text)
    if comment_match:
        return unescape(comment_match.group(1).strip())

    root = ElementTree.fromstring(svg_text)
    for element in root.iter():
        tag_name = element.tag.split("}", 1)[-1]
        if tag_name not in {"metadata", "desc"}:
            continue
        element_id = str(element.attrib.get("id", "") or "").strip().lower()
        if element_id not in {"vpinplay-payload", "vpinplay-payload-desc"}:
            continue
        if element.text and element.text.strip():
            return unescape(element.text.strip())

    raise ValueError("Could not find embedded VPinPlay payload in the uploaded SVG.")


def _load_payload_text(filename: str, content: bytes) -> str:
    name = str(filename or "").strip()
    if not content:
        raise ValueError("Uploaded file is empty.")

    try:
        text = content.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ValueError("Uploaded file must be a UTF-8 SVG generated by VPinFE.") from exc

    stripped = text.strip()
    if stripped.startswith("{"):
        return stripped
    if "<svg" in stripped:
        return _extract_payload_text_from_svg(stripped)

    suffix = name.rsplit(".", 1)[-1].lower() if "." in name else ""
    if suffix and suffix != "svg":
        raise ValueError("Only VPinFE-generated SVG QR files are supported right now.")
    raise ValueError("Uploaded file is not a supported VPinPlay QR SVG.")


def activate_profile_from_upload(filename: str, content: bytes) -> dict[str, Any]:
    payload_text = _load_payload_text(filename, content)
    try:
        payload = json.loads(payload_text)
    except json.JSONDecodeError as exc:
        raise ValueError("Embedded VPinPlay payload is not valid JSON.") from exc

    validated = validate_profile_payload(payload)
    return activate_alternate_profile(validated, source_name=filename)


def clear_profile() -> dict[str, Any]:
    return clear_alternate_profile()


def clear_profile_by_key(profile_key: str) -> dict[str, Any]:
    return clear_alternate_profile(profile_key)


def set_current_profile(profile_key: str) -> dict[str, Any]:
    return set_active_profile(profile_key)


def get_profile_status() -> dict[str, Any]:
    return get_alternate_profile_state()
